# Generated by Django 4.2.15 on 2024-09-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='costumer',
            new_name='custumer',
        ),
    ]
