# Generated by Django 4.2.15 on 2024-09-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_cartitem_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
