# Generated by Django 4.2.15 on 2024-09-02 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cpu_brand', models.CharField(choices=[('INTEL', 'Intel'), ('AMD', 'AMD'), ('IBM', 'IBM'), ('APPLE', 'Apple'), ('QUALCOMM', 'Qualcomm'), ('ARM', 'ARM'), ('NVIDIA', 'Nvidia'), ('MEDIATEK', 'MediaTek'), ('TEXAS_INSTRUMENTS', 'Texas Instruments')], default='INTEL', max_length=220)),
                ('cpu_series', models.CharField(max_length=220)),
                ('cpu_model', models.CharField(max_length=220)),
                ('cpu_generation', models.IntegerField()),
                ('cpu_sku', models.CharField(max_length=50)),
                ('total_cores', models.IntegerField()),
                ('performance_cores', models.IntegerField(blank=True, null=True)),
                ('efficiency_cores', models.IntegerField(blank=True, null=True)),
                ('threads', models.IntegerField()),
                ('base_clock_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boost_clock_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('l1_cache', models.DecimalField(decimal_places=2, max_digits=5)),
                ('l2_cache', models.DecimalField(decimal_places=2, max_digits=5)),
                ('l3_cache', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tdp', models.IntegerField()),
                ('max_operating_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('has_integrated_graphics', models.BooleanField(default=False)),
                ('integrated_graphics_model', models.CharField(blank=True, max_length=220, null=True)),
                ('integrated_graphics_max_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lithography', models.IntegerField()),
                ('release_date', models.DateField()),
                ('supports_hyperthreading', models.BooleanField(default=False)),
                ('supports_virtualization', models.BooleanField(default=True)),
                ('supports_overclocking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gpu_brand', models.CharField(max_length=220)),
                ('gpu_series', models.CharField(max_length=220)),
                ('gpu_model', models.CharField(max_length=220)),
                ('memory_size', models.IntegerField()),
                ('memory_type', models.CharField(max_length=50)),
                ('memory_clock_speed', models.IntegerField()),
                ('core_clock_speed', models.IntegerField()),
                ('boost_clock_speed', models.IntegerField(blank=True, null=True)),
                ('cuda_cores', models.IntegerField(blank=True, null=True)),
                ('stream_processors', models.IntegerField(blank=True, null=True)),
                ('tdp', models.IntegerField()),
                ('interface', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ram_brand', models.CharField(max_length=220)),
                ('ram_type', models.CharField(max_length=50)),
                ('ram_size', models.IntegerField()),
                ('ram_speed', models.IntegerField()),
                ('cas_latency', models.IntegerField()),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('form_factor', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LaptopProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=220)),
                ('model', models.CharField(max_length=220)),
                ('series', models.CharField(max_length=220)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('usage', models.CharField(choices=[('general', 'عمومی'), ('Ai', 'هوش  مصنوعی'), ('backend_devops', 'برنامه نویس  بکند و فرانت و دواپس'), ('graphic', 'گرافیک'), ('architecture', 'معماری'), ('enginiering', 'مهندسی'), ('iot', 'iot')], default='general', max_length=220)),
                ('description', models.TextField(blank=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cpu')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gpu')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ram')),
                ('user_maker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_admin_laptop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
