# Generated by Django 4.2.15 on 2024-09-02 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopproduct',
            name='gpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_laptops', to='products.gpu'),
        ),
        migrations.AlterField(
            model_name='laptopproduct',
            name='user_maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_admin_laptops', to=settings.AUTH_USER_MODEL),
        ),
    ]
