# Generated by Django 4.2.15 on 2024-09-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_laptopproduct_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(max_length=220)),
                ('country', models.CharField(max_length=220)),
            ],
        ),
        migrations.AlterField(
            model_name='laptopproduct',
            name='brand',
            field=models.ForeignKey(default='China', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.brand'),
        ),
    ]
