# Generated by Django 4.2.15 on 2024-09-05 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopproduct',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
        ),
    ]
