# Generated by Django 4.2.15 on 2024-09-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_laptopproduct_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopproduct',
            name='battery',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='laptopproduct',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laptopproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
